name: Benchmark Snapshot

on: workflow_dispatch

jobs:
      
  screenshots:
    name: Screenshot Reliability
    runs-on: ubuntu-latest

    steps:
      - name: Set current Date
        shell: bash
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Snapshot Mainnet Reliability
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.alohaeos.com/tools/reliability#networkId=11&timeframeId=8&sort=rank&sortDir=asc
          destination: mainnet-reliability-${{ env.NOW }}.png
          full-page: true
          delay: 20
          width: 1440

  upload:
    name: Commit Screenshots
    runs-on: ubuntu-latest
    needs: [screenshots]
    
    steps:
      - name: Set current Date
        shell: bash
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'
          
      - name: Create Snapshot Directory
        run: mkdir -p data/benchmarks/${{ env.NOW }}

      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: mainnet-reliability-${{ env.NOW }}
          path: data/benchmarks/${{ env.NOW }}
      
      - name: Debug structure of downloaded files
        run: ls -R
        
      - name: Git add Files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Adding Snapshots ${{ env.NOW }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        
        
    
        
    
    
