name: Benchmark Snapshot

on: workflow_dispatch

jobs:
  screenshot:
    name: Screenshot Reliability
    
    runs-on: ubuntu-latest

    steps:
    
    - name: Set current Date
      shell: bash
      run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Snapshot Mainnet Reliability
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://www.alohaeos.com/tools/reliability#networkId=11&timeframeId=8&sort=rank&sortDir=asc
        destination: mainnet-reliability-${{ env.NOW }}.png
        full-page: true
        delay: 20
        width: 1440
        
    
    
