name: Guild Lottery

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
          working-directory: ./guild-lottery
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
      - run: npm ci
        working-directory: ./guild-lottery
      - run: npm run lottery --if-present
        working-directory: ./guild-lottery
