name: Guild Lottery

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./notion-tools

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './notion-tools/package-lock.json'
      - name: Create .env file
        run: echo "NOTION_API_KEY=${{ secrets.NOTION_API_KEY }}" > .env
      - name: Install dependencies
        run: npm ci
      - name: Run Notion Scores
        run: npm run start --if-present
